spring:
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        open-in-view: off
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 1000
    profiles:
        active: mysql
server:
    port: 9090



---
spring:
    jpa:
        hibernate:
            ddl-auto: create
    config:
        activate:
            on-profile: dev
    h2:
        console:
            enabled: true



---
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/shortcut
        username: root
        password: PASSWORD
    config:
        activate:
            on-profile: mysql