spring:
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        open-in-view: off
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 1000
    profiles:
        active: mysql
domain:
    url: http://127.0.0.1
server:
    port: 80
springdoc:
    api-docs:
        path: /api-doc
    swagger-ui:
        path: /swagger-ui
        disable-swagger-default-url: true

---
spring:
    jpa:
        hibernate:
            ddl-auto: create
    config:
        activate:
            on-profile: dev
    h2:
        console:
            enabled: true
            path: /h2



---
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/shortcut
        username: root
        password: PASSWORD
    config:
        activate:
            on-profile: mysql
---
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysqlDB:3306/shortcut
        username: root
        password: password
    config:
        activate:
            on-profile: docker