version: "3.1"
services:
    was:
        image: votm777/shortest:1.0
        ports:
            - "80:80"
        depends_on:
            - database
        restart: always
        networks:
            - backend

    database:
        image: mysql:latest
        container_name: mysqlDB
        ports:
            - "3306:3306"
        volumes:
            - "./sql/:/docker-entrypoint-initdb.d/"
        environment:
            MYSQL_DATABASE: shortcut
            MYSQL_ROOT_PASSWORD: password
        networks:
            - backend

networks:
    backend:
        driver: bridge